name: CI tracking-reports

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  review-build-and-test:
    if: ${{ github.repository == 'Maur025/tracking-report-nest' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2.0.0
        with:
          runtime: node@24
          cache: true

      - name: Code check
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build project
        run: pnpm build
